# Generated by Django 4.2.30 on 2026-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0005_auto_20240606_0143"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacomponent",
            name="data_source_ref",
        ),
        migrations.AddField(
            model_name="datacomponent",
            name="mitre_id",
            field=models.CharField(default="X0000", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datacomponent",
            name="mitre_url",
            field=models.URLField(default="https://attack.mitre.org/datacomponents/X0000/"),
            preserve_default=False,
        ),
    ]
