# Generated by Django 4.2.30 on 2026-06-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0006_remove_datacomponent_data_source_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacomponent",
            name="log_sources",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
