# Generated by Django 4.2.30 on 2026-06-21 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0007_datacomponent_log_sources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technique",
            name="data_sources",
        ),
        migrations.RemoveField(
            model_name="technique",
            name="detection_description",
        ),
        migrations.RemoveField(
            model_name="technique",
            name="permissions_required",
        ),
        migrations.RemoveField(
            model_name="technique",
            name="system_requirements",
        ),
    ]
