# Generated by Django 4.2.30 on 2026-06-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0008_remove_technique_data_sources_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mitre_id", models.CharField(max_length=255)),
                ("mitre_url", models.URLField()),
                ("mitre_stix_identifier", models.CharField(max_length=255, unique=True)),
                ("mitre_original_data", models.JSONField()),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("deprecated", models.BooleanField(default=False)),
                ("revoked", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=16)),
                ("contributors", models.JSONField(blank=True, null=True)),
                ("platforms", models.JSONField()),
                ("domains", models.JSONField()),
                ("sectors", models.JSONField(blank=True, null=True)),
                ("related_assets", models.JSONField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mitreattack.collection"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
