# Generated by Django 4.2.30 on 2026-06-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0010_analytic"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mitre_id", models.CharField(max_length=255)),
                ("mitre_url", models.URLField()),
                ("mitre_stix_identifier", models.CharField(max_length=255, unique=True)),
                ("mitre_original_data", models.JSONField()),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("deprecated", models.BooleanField(default=False)),
                ("revoked", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=16)),
                ("contributors", models.JSONField(blank=True, null=True)),
                ("domains", models.JSONField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mitreattack.collection"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="analytic",
            name="detection_strategy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="mitreattack.detectionstrategy",
            ),
        ),
    ]
