# Generated by Django 4.2.30 on 2026-06-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0011_detectionstrategy_analytic_detection_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("channel", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "analytic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_sources",
                        to="mitreattack.analytic",
                    ),
                ),
                (
                    "data_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="mitreattack.datacomponent",
                    ),
                ),
            ],
        ),
    ]
