# Generated by Django 4.2.30 on 2026-06-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0012_logsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analytic",
            name="data_components",
            field=models.ManyToManyField(
                blank=True, related_name="analytics", to="mitreattack.datacomponent"
            ),
        ),
    ]
