# Generated by Django 4.2.30 on 2026-06-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mitreattack", "0013_alter_analytic_data_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsource",
            name="channel",
            field=models.CharField(max_length=511),
        ),
    ]
